import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from 'components/Header'
import UserInfo from 'components/UserInfo'
import Advertisement from 'components/Advertisement'
import Login from 'components/Login'
import Feed from 'components/Feed'
import { getSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({session}) {
  if(!session) return <Login/>
  return (
    <>
      <Head>
        <title>Beano.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/beano_logo.jpg" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <script src="https://kit.fontawesome.com/71c6f6e96c.js" crossOrigin="anonymous"></script>
        <link rel="stylesheet" href="https://kit.fontawesome.com/71c6f6e96c.css" crossOrigin="anonymous"></link>
      </Head>
      <main>
        <Header/>
        <div className="content flex-row justify-content-between">
          <UserInfo/>
          <Feed/>
          <Advertisement/>
        </div>
      </main>
    </>
  )
}
export async function getServerSideProps(context){
  const session = await getSession(context)
  return {
    props: {session}
  }
}
